on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    env:
      REPO : serv
      VLNV : serv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: serv
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint $VLNV
